SELECT OBJECT_TYPE, OBJECT_SCHEMA, OBJECT_NAME, LOCK_TYPE, LOCK_STATUS, THREAD_ID, 
PROCESSLIST_ID, PROCESSLIST_INFO,PROCESSLIST_USER,PROCESSLIST_HOST,PROCESSLIST_DB,PROCESSLIST_COMMAND,CONNECTION_TYPE 
FROM performance_schema.metadata_locks 
INNER JOIN performance_schema.threads ON THREAD_ID = OWNER_THREAD_ID 
INNER JOIN INFORMATION_SCHEMA.INNODB_TRX ON PROCESSLIST_ID = trx_mysql_thread_id
WHERE PROCESSLIST_ID <> CONNECTION_ID() and trx_started < CURRENT_TIMESTAMP - INTERVAL 60 SECOND;